<?php

declare(strict_types=1);

namespace ScottKeckWarren\Kanine\Config;

use Symfony\Component\Console\Helper\QuestionHelper;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\ConfirmationQuestion;
use Symfony\Component\Console\Question\Question;

final class ConfigInitializer implements ConfigInitializerInterface
{
    private readonly string $dotKanineDir;
    private readonly string $configPath;

    public function __construct(private readonly string $baseDir = '')
    {
        $base               = $baseDir !== '' ? $baseDir : (getcwd() ?: '');
        $this->dotKanineDir = $base . '/.kanine';
        $this->configPath   = $this->dotKanineDir . '/kanine.yaml';
    }

    public function configExists(): bool
    {
        return file_exists($this->configPath);
    }

    /**
     * @param array{token_env: string, repositories: list<string>} $data
     */
    public function write(array $data): void
    {
        if (!is_dir($this->dotKanineDir)) {
            mkdir($this->dotKanineDir, 0777, true);
        }

        $content = $this->buildYaml($data['token_env'], $data['repositories']);
        file_put_contents($this->configPath, $content);
    }

    public function run(InputInterface $input, OutputInterface $output): void
    {
        $helper = new QuestionHelper();

        if ($this->configExists()) {
            $question = new ConfirmationQuestion(
                'Config already exists at .kanine/kanine.yaml. Overwrite? [y/N] ',
                false,
            );

            if (!$helper->ask($input, $output, $question)) {
                throw new \RuntimeException('Aborted');
            }
        }

        $tokenEnvQuestion = new Question(
            'Which environment variable holds your GitHub token? [GITHUB_TOKEN]: ',
            'GITHUB_TOKEN',
        );
        $tokenEnv = (string) $helper->ask($input, $output, $tokenEnvQuestion);

        $repositories = $this->collectRepositories($input, $output, $helper);

        $this->write([
            'token_env'    => $tokenEnv,
            'repositories' => $repositories,
        ]);

        $output->writeln("Config written to .kanine/kanine.yaml — run 'kanine serve' to start.");
    }

    /**
     * @return list<string>
     */
    private function collectRepositories(
        InputInterface $input,
        OutputInterface $output,
        QuestionHelper $helper,
    ): array {
        $repositories = [];

        while (true) {
            $question = new Question('Repository (owner/repo, blank to finish): ');
            $entry    = (string) $helper->ask($input, $output, $question);

            if ($entry === '') {
                if (count($repositories) === 0) {
                    $output->writeln('<error>At least one repository is required.</error>');
                    continue;
                }
                break;
            }

            if (!preg_match('/^[^\/]+\/[^\/]+$/', $entry)) {
                $output->writeln("<error>Invalid format: {$entry}. Use owner/repo.</error>");
                continue;
            }

            $repositories[] = $entry;
        }

        return $repositories;
    }

    /**
     * @param list<string> $repositories
     */
    private function buildYaml(string $tokenEnv, array $repositories): string
    {
        $repoLines = '';
        foreach ($repositories as $repo) {
            $repoLines .= "    - {$repo}\n";
        }

        return <<<YAML
            # .kanine/kanine.yaml — generated by kanine init

            github:
              repositories:
            {$repoLines}  token_env: {$tokenEnv}
              ready_label: "kanine: ready"

            supervisor:
              host: 127.0.0.1
              port: 3737

            # log_file: var/log/kanine.log   # optional; omit to disable file logging
            YAML;
    }
}
